### ISSUE TITLE
Output Errors Parsing Wikipedia Articles XML

### ISSUE THREAD

**Issue by traviscollins** [georgyfarniev/xmlkit#5]
I am attempting to use this library to read "pages" from the [Wikimedia Articles download](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2). 

```typescript
import * as fs from "fs";
import { default as bz2 } from "unbzip2-stream";
import { XmlStream } from "xmlkit";

async function main() {
  const xmlParser = new XmlStream("mediawiki.page");

  const xml = fs
    .createReadStream(
      "enwiki-latest-pages-articles.xml.bz2"
    )
    .pipe(bz2())
    .pipe(xmlParser);

  for await (const chunk of xml) {
    console.log("chunk:" + chunk);
  }
}

await main();
```

The first output chunk includes portions of the original XML not included in the "mediawiki.page" selector, with starting tags missing. 

```
chunk:
  
    Wikipedia</sitename>
    enwiki</dbname>
    https://en.wikipedia.org/wiki/Main_Page</base>
    MediaWiki 1.43.0-wmf.20</generator>
    first-letter</case>
    
      Media</namespace>
      Special</namespace>
      </namespace>
      Talk</namespace>
      User</namespace>
      User talk</namespace>
 (...deleted for readability....)
  </siteinfo>
````

**Comment by traviscollins** [comment]
My current work around is to "skip the first chunk". Seems to work ok.

**Comment by georgyfarniev** [comment]
Hello Travis, thank you for reporting the issue. I will try to allocate time to debug it this evening.

**Comment by georgyfarniev** [comment]
Travis, this issue was addressed in PR https://github.com/georgyfarniev/xmlkit/pull/6, thank you for using my module. Do not hesitate to come back with other issues or requests. Also, please let me know  if the fix is working for you. To prevent potentially breaking change at least for you to be an issue, I published this fix as a major update version number.
